In [1]:
import numpy as np

1. Buatlah Tensor di bawah ini dengan Python:
    23 50   57 67
    7  12   99 43

    75 21   87 26
    57 12   18 84




In [3]:
from numpy import array
T = array([[[[23,50],[7,12]],[[57,67],[99,43]]],[[[75,21],[57,12]],[[87,26],[18,84]]]])
print(T.shape)
print(T)

(2, 2, 2, 2)
[[[[23 50]
   [ 7 12]]

  [[57 67]
   [99 43]]]


 [[[75 21]
   [57 12]]

  [[87 26]
   [18 84]]]]


2. Lakukan perkalian terhadap matrix berikut:
  A = 23 50 19
      7  12 109
      57 67 98, 
      
  B = 17
      22
      19


In [7]:
A = np.array([[23,50,19],
              [7,12,109],
              [57,67,98]])
B = np.array([[17],[22],[19]])
B

array([[17],
       [22],
       [19]])

In [8]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [9]:
A @ B

array([[1852],
       [2454],
       [4305]])

3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix di bawah ini:
A = 23 50 19
    7  12 109
    57 67 98


In [10]:
C = A.T
print(C)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [13]:
deter = np.linalg.det(A)
print(deter)

131344.0000000002


In [14]:
A_invers = np.linalg.inv(A)
A_invers

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])